# Dockerfile.Consumidor
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Consumidor/Consumidor.csproj"
RUN dotnet publish "Consumidor/Consumidor.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080  # Adicione esta linha
ENTRYPOINT ["dotnet", "Consumidor.dll"]