name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Produtor/Produtor.csproj

      - name: Build the project
        run: dotnet build Produtor/Produtor.csproj --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish Produtor/Produtor.csproj --configuration Release --no-build --output out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Validate Docker Username
        run: |
          if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "DOCKER_USERNAME is not set. Please configure it in GitHub Secrets."
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/atualizacontatos:latest
